all:
  hosts:
    target_host:
      ansible_host: "{{ lookup('env', 'TARGET_HOST') }}"
      ansible_user: "{{ lookup('env', 'SSH_USER') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_PATH') }}"